
CREATE DATABASE DB_STOCKMARKET;

USE DB_STOCKMARKET;

CREATE TABLE TBL_COMPANY(
		SYMBOL VARCHAR(7) PRIMARY KEY,
		LONGNAME VARCHAR(30) NOT NULL,
		SECTOR VARCHAR(30) NOT NULL,
		CURRENTPRICE FLOAT NOT NULL
);

CREATE TABLE TBL_STOCKPRICE(
		SNO INT IDENTITY(1,1) PRIMARY KEY,
		SYMBOL VARCHAR(7) REFERENCES TBL_COMPANY(SYMBOL),
		DATE DATETIME NOT NULL,
		OPENPRICE FLOAT NOT NULL,
		HIGHPRICE FLOAT NOT NULL,
		LOWPRICE FLOAT NOT NULL,
		CLOSEPRICE FLOAT NOT NULL,
		ADJCLOSE FLOAT NOT NULL,
		VOL FLOAT NOT NULL
		);

CREATE TABLE TBL_DIVIDENDS(
		SNO INT PRIMARY KEY,
		SYMBOL VARCHAR(7) REFERENCES TBL_COMPANY(SYMBOL),
		DATE DATETIME NOT NULL,
		DIVIDENDS FLOAT NOT NULL
		);


BULK INSERT TBL_COMPANY
FROM 'C:\Users\dell\OneDrive\Desktop\Uni\Database-Project\TBL_COMPANY.csv'
WITH (
		FORMAT = 'CSV'
);

BULK INSERT TBL_STOCKPRICE
FROM 'C:\Users\dell\OneDrive\Desktop\Uni\Database-Project\TBL_STOCKPRICE.csv'
WITH (
		FORMAT = 'CSV'
);

BULK INSERT TBL_DIVIDENDS
FROM 'C:\Users\dell\OneDrive\Desktop\Uni\Database-Project\TBL_DIVIDENDS.csv'
WITH (
		FORMAT = 'CSV'
);


CREATE INDEX IDX_STOCKPRICE
ON TBL_STOCKPRICE(SYMBOL,CLOSEPRICE,VOL);

CREATE INDEX IDX_DIV
ON TBL_DIVIDENDS(SYMBOL,DATE,DIVIDENDS);


CREATE VIEW VW_SUMMARY AS
	SELECT COM.LONGNAME,
		   COM.SYMBOL,
		   COM.SECTOR,
		   MAX(DIV.DIVIDENDS) AS MAXDIV,
		   MAX(ST.CLOSEPRICE) AS MAXCLOSE
	FROM TBL_COMPANY COM
	INNER JOIN TBL_STOCKPRICE ST ON ST.SYMBOL = COM.SYMBOL
	INNER JOIN TBL_DIVIDENDS DIV ON ST.SYMBOL = DIV.SYMBOL
	GROUP BY COM.LONGNAME,COM.SECTOR,COM.SYMBOL;


CREATE TABLE PREDICTIONS(
			OPENPRICE FLOAT NOT NULL,
			HIGHPRICE FLOAT NOT NULL,
			LOWPRICE FLOAT NOT NULL,
			ADJCLOSE FLOAT NOT NULL,
			VOL FLOAT NOT NULL,
			CLOSEPRICE FLOAT NOT NULL,
			SYMBOL VARCHAR(7) REFERENCES TBL_COMPANY(SYMBOL),
			DATE DATE NOT NULL );


CREATE TABLE PREDICTIONS_AUDIT(
			SYMBOL VARCHAR(7) NOT NULL REFERENCES TBL_COMPANY(SYMBOL),
			CLOSEPRICE FLOAT NOT NULL,
			AUDIT_ACTION VARCHAR(20),
			AUDIT_TIMESTAMP DATETIME
		);


CREATE TRIGGER trgAfterInsert ON PREDICTIONS
FOR INSERT
AS
	DECLARE @sym VARCHAR(10);
	DECLARE @closepr FLOAT;
	DECLARE @audit_action VARCHAR(20);

	SELECT @sym=i.SYMBOL FROM inserted i;	
	SELECT @closepr=i.CLOSEPRICE FROM inserted i;	
	SET @audit_action='Inserted Record -- After Insert Trigger.';

	insert into PREDICTIONS_AUDIT
           (SYMBOL,CLOSEPRICE,AUDIT_ACTION,AUDIT_TIMESTAMP) 
	values(@sym,@closepr,@audit_action,getdate());

	PRINT 'AFTER INSERT trigger fired.'
GO
